osx_image: xcode15.4
language: objective-c

install:
  - bundle install
  - cd Tests
  - bundle exec pod install --project-directory=./iOS
  - bundle exec pod install --project-directory=./Mac
  - cd ../

script:
  - export IOS_VERSION="17.5.1"
  - bash Tests/test-all.sh
  - swift build
  - swift test
  - bundle exec pod lib lint
  - carthage build --no-skip-current && for platform in Mac iOS tvOS; do test -d Carthage/Build/${platform}/CocoaAsyncSocket.framework || exit 1; done
